# to take the input of six numbers from the user and print them as a sequence in a set.
s=set()
a=input("Enter the first number:")
s.add(int(a))
b=input("Enter the second number:")
s.add(int(b))
c=input("Enter the third number:")
s.add(int(c))
d=input("Enter the fourth number:")
s.add(int(d))
e=input("Enter the fifth number:")
s.add(int(e))
f=input("Enter the sixth number:")
s.add(int(f))
g=input("Enter the seventh number:")
s.add(int(g))

print(s)