#include <stdio.h>
int main()
{
	const int n;
	printf("ENTER ANY NUMBER OF YOUR CHOICE:");
	scanf("%d",&n);
	printf("THE VALUE ENTERED IS: %d",n);
//	n=n+10;   COMPILATION ERROR AS WE ARE TRYING TO REINITIALIZE THE VAIABLE WHICH IS DECLARED WITH CONST.              
//WAP TO CHECK IF A NUMBER IS POSITIVE OR NEGATIVE USING THE TERNARY IF ELSE OPAERATOR
//  ALWAYS DECLARE AND INITIALIZE A VARIABLE WITH CONST IN THE SAME LINE.
	printf("THE UPDATED VALUE IS: %d",n);
	return 0;
}
