// TO TAKE THE LIMIT AS INPUT FROM TH USER AND PRINT ALL THE EVEN VALUES FROM 0 TO THAT PARTICULAR NUMBER PROVIDED BY THE USER. 
let n=prompt("ENTER A NUMBER:");
for (let i=0;i<=n;i+=2){
    console.log("i=",i);
}
console.log("EVEN NUMBERS PRINTED");
alert("NUMBERS PRINTED SUCCEAFULLY !");