from fpdf import FPDF

# Initialize PDF
pdf = FPDF('P', 'mm', 'A4')
pdf.set_auto_page_break(auto=True, margin=15)

# Cover Page
pdf.add_page()
pdf.set_font("Arial", 'B', 24)
pdf.set_text_color(0, 102, 204)
pdf.cell(0, 60, "Computer System MCQs", ln=True, align='C')
pdf.set_font("Arial", '', 18)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 20, "With Answers and Explanations", ln=True, align='C')
pdf.ln(60)
pdf.set_font("Arial", 'I', 12)
pdf.cell(0, 10, "Generated by ChatGPT", ln=True, align='C')

# Example: Replace this with the full 180 questions as a list of strings
questions = [
    "1. Which component is considered the brain of the computer?\nA) GPU\nB) CPU\nC) RAM\nD) HDD\nAnswer: B) CPU\nExplanation: The CPU executes instructions and processes data, functioning as the brain of the computer.",
    "2. RAM is an example of:\nA) Volatile memory\nB) Non-volatile memory\nC) Secondary storage\nD) Cache\nAnswer: A) Volatile memory\nExplanation: RAM loses data when power is turned off, making it volatile.",
    # ... Add all 180 questions in this format ...
]

# Function to add questions
def add_questions(title, questions_list):
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 10, title, ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(0, 0, 0)
    for q in questions_list:
        pdf.multi_cell(0, 7, q + "\n")
        pdf.ln(2)

# Add all sections manually or programmatically
# Example: Adding easy questions (replace with all sections)
add_questions("Easy Questions (1-40)", questions[:40])
add_questions("Moderate Questions (41-110)", questions[40:110])
add_questions("Difficult Questions (111-180)",_
